version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: project_prosnab_redis
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: project_prosnab_backend
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    ports:
      - "8002:8000"
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_NAME=prosnab_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=0#T%2
      - DATABASE_PORT=5435
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ALLOWED_HOSTS=*
      - DEBUG=1
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis

  worker:
    build: .
    container_name: project_prosnab_worker
    command: celery -A prosnabdb worker -l info
    volumes:
      - .:/app
      - media_volume:/app/media
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_NAME=prosnab_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=0#T%2
      - DATABASE_PORT=5435
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
      - backend

  frontend:
    build: ./frontend
    container_name: project_prosnab_frontend
    ports:
      - "3006:80"
    volumes:
      - media_volume:/app/media
      - static_volume:/app/static
    depends_on:
      - backend

volumes:
  media_volume:
  static_volume:
